### PR TITLE
Move generic text functions to draw2dbase

### PR DESCRIPTION
**Pull request by redstarcoder**
This change moves all the `draw2dimg` text methods to `draw2dbase` and integrates them into `StackGraphicContext`. This reduces repeated code from `draw2dimg` and `draw2dgl`. This should be helpful for adding caches too.

### CODE REVIEW

**Comment by redstarcoder** [comment]
With caches implemented, it doesn't look like they rely on these changes at all, I just think they make them look more consistent, keeping the text methods in one spot. There are a lot of ways I could have organized this though so, please don't hesitate to give your opinion!

I still think the biggest gain here is the reduced repeated code. All future gcs that get created, if they use identical text methods, won't have to include a decent chunck of code.

**Comment by llgcode** [comment]
I'm no sure all gc needs these defaults methods.

**Comment by redstarcoder** [comment]
What's the downside to giving gcs default font methods? Once the gc specifys their own method (which right now, would be just `draw2dpdf`) the default method would be hidden by the interface anyways (unless type asserted, then accessed directly by `gc.StackGraphicContext`).

The only thing I can think of is maybe the binary would be a bit bigger for the extra code that would always be included.

-----------

I could migrate the code somewhere else, maybe still keeping it in `draw2dbase`, but no longer part of the `StackGraphicContext` (probably moving the method out of `stack_gc.go` and into something like `text.go`). 

For example the defaults

```go
func (gc *StackGraphicContext) loadCurrentFont() (*truetype.Font, error) {}
func (gc *StackGraphicContext) CreateStringPath(s string, x, y float64) float64 {}
```

would become

```go
func loadCurrentFont(gc *draw2d.GraphicContext) (*truetype.Font, error) {}
func CreateStringPath(gc *draw2d.GraphicContext, s string, x, y float64) float64 {}
```

That way they wouldn't be included unless actually referenced inside the gc package via a call like `draw2dbase.CreateStringPath`. I'd also be able to put default `FillStringAt` and `StrokeStringAt` functions into #118 as I wouldn't be restricted to the `StackGraphicContext` methods.

**Comment by llgcode** [comment]
I like your solution to extract CreateStringPath to an external function, this way it can be used as an utility, but we have to be sure that nobody use it! We have to check this. 
Thanks for your work :)

**Comment by redstarcoder** [comment]
I have pushed changes. These changes add four new methods to the `GraphicContext` interface for getting and setting the scale, and the actual `truetype.Font`, but it removes the default methods from the `StackGraphicContext`. I could also reorganize this by maybe removing `Scale` and `Font` and extending `FontData` to include them. Let me know what you think!

Happy to help :)

**Comment by llgcode** [comment]
The only thing that we need is FontSize. Scale is an internal variable of Context and do not have to be exposed in Gc Interface. SetDPI(dpi int) and GetDPI() int have to be removed from the Gc interface too, it's too specific to draw2dimg.
Happy to collaborate :)

**Comment by redstarcoder** [comment]
@llgcode, I agree in principal (limiting what's in the `GraphicContext` interface), but for interacting with text `Scale` ends up being useful (specifically for factoring in kerning). Perhaps we should have a method for returning the result of `fUnitsToFloat64(f.Kern(fixed.Int26_6(gc.Current.Scale), prev, index))`? It could accept prev and index as arguments, not sure what to name it though...

Also `DPI1 is currently also used in `draw2dgl` for calculating the scale in `recalc`. Was this a mistake? Should I change `float64(gc.DPI)` to a constant?

If we do use `DPI` in `draw2dgl`, perhaps we could make public and rename `recalc`, and then remove the DPI methods from the interface?

**Comment by llgcode** [comment]
We have to be careful when removing method of this interface. We have to communicate (make it depcated) and to be sure to have an alternative if someone use it. Yes I think it's a mistake to have DPI in Gc interface, it is just a parameter of a constructor or an option of specific Gc . Scale in this context is too much specific for font coming from freetype it can't be part of Gc interface.

**Pull request closed without merging**
