### PR TITLE
Draw2dgl with go gl

### PR DESCRIPTION
**Pull request by sbinet**
- use `github.com/go-gl/{gl,glfw}`
- de-stutter types
- remove `GLVertex`
- add plumbing for `draw2dgl` in `Makefile`

### CODE REVIEW

**Comment by llgcode** [comment]
I've merged your work but. It compiles and open a glfw window but it display a black window on my win7 laptop

**Comment by llgcode** [comment]
fixed works on win7

**Comment by sbinet** [comment]
`go run ./cmd/roundedrectgl.go` on linux too :)

there will probably some need to channel the `OpenGL` commands on the main goroutine for `OpenGL`'s sake (which requires that)

this will be yet another PR.
but week-end's calling!

**Comment by llgcode** [comment]
not sure. it's seems to work now.
I don't know really what this function does 
```go
// GLFW event handling must run on the main OS thread
runtime.LockOSThread()
```
but it seems to do the trick the display function is always called from the same goroutine. I fix the issue: the opengl context was not initialized. I just call reshape function (that function init gl context at the right size) before display loop.

**Comment by sbinet** [comment]
it is indeed for gonum/plot. see my work-in-progress PR: gonum/plot#197.

glad I could be of some help.

**Pull request merged**
