### PR TITLE
Feature/svg context

### PR DESCRIPTION
**Pull request by Drahoslav7**
Implementation of SVG drawing context
related to #107 

@llgcode Do not merge yet. Only creating this for you can check my progress if you want to.

Only some things work for now.
I'll keep this list up to date:
 - [x] path
    - [x] definitions
      - [x] move to
      - [x] line to
      - [x] cubic curve to
      - [x] quad curve to
      - [x] arc to
      - [x] close
    - [x] fill color
    - [x] fill rule
    - [x] stroke color
    - [x] line width
    - [x] cap
    - [x] join
    - [x] dash
    - [x] dash offset
  - [x] transformation
 - [ ] text
   - [x] fill
   - [x] stroke
   - [x] font size
   - [ ] font data
   - [x] string bounds
   - [x] string path
   - [ ] ...
 - [x] dpi
 - [x] clear
 - [x] clear rect
 - [x] draw (raster) image
 - [ ] ...

### CODE REVIEW

**Comment by llgcode** [comment]
Hi @Drahoslav7,
Really nice implementation.
Some notes:
- doc.go: remove the reference to svgo
- type SVG bytes.Buffer not used
- ...
Merry Chrismas.

**Comment by Drahoslav7** [comment]
Thank you, @llgcode.
Merry Christmas to you too!

**Comment by Drahoslav7** [comment]
So, this is almost finished.
You can do a code review and give me some feedback.
Only thing I'm not sure about is the fonts.

There are several ways how to handle fonts in SVG files. I think there should be implemented more of them.

The possibilities I can think of are:

1) system font - reference to name of font installed in OS
	+ does not actual need font in fontcache at all when generating svg
	- only makes sense for commonly used fonts

2) link font file
	- includes css
	- separated file(s) needs to be distributed with image
          (but this file may not be always available, and it can't be generated from fontCache, because raw TTF data is not accessible in current implementation)

3) embeded svg font - using `<font>` and related tagg in `<defs>`
	+ this I like the most
	+ it only need to actually embed glyphs which are used in text
	- poor browser support :(

4) embeded ttf/woff font
	+ good browser support
	- includes css
	- bigger size - base64 used for encoding font
	- hard to implement, not sure how should the raw ttf or woff data be generated from current api (freetype/truetype) if it is even possible

5) text converted to path
	+ best support accross platforms - always displayed correctly
	- text is path not text - is not editable or copyable
	- big file size (use `<use>` for each character to reduce repeating?)


I actually already implemented option 3 and 5.

Can you give me your opinion on this issue, @llgcode?

**Comment by llgcode** [comment]
Hi @Drahoslav7,
Thanks for your work, you did a really good job! Sorry this an open source project I can't give you anything but Thanks. Feel free to add your name in https://github.com/llgcode/draw2d/blob/master/AUTHORS file.

For font, it's really interesting to embed font or transform text to path to be sure to have high fidelity image. What about the 1st case using font family and common font style.

Another option for raster image would be to be able to save it relative to the svg (it could be an option of the SVG GraphicContext) and add options to serialize the image with different format. 

I can merge the pull request and open 2 issues.

**Comment by Drahoslav7** [comment]
Thank you.

Alright, you can merge this and open new issues which I will try solve later :)

Good point with the raster images.

**Pull request merged**
