### PR TITLE
Change .NewGraphicContext package.

### PR DESCRIPTION
**Pull request by stephenwithav**
NewGraphicContext is also now in draw2dimg.

### CODE REVIEW

**Comment by stephenwithav** [comment]
Is there a roadmap for this project?

I'm implementing an SVG renderer with draw2d, so I'd be happy to contribute where I can.

**Comment by llgcode** [comment]
oh, great!
yes, you might want to contact Stani Michiels <https://github.com/stanim> that
wants to implement an svg gc too. I don't know if he started to implement.
He implements the pdf gc.
thx stephen

-- Laurent.

**Comment by stephenwithav** [comment]
Thanks for the heads up!

**Comment by stanim** [comment]
@llgcode
Are we not breaking backwards compatibility now? I agree with the merged changes but I am afraid this will cause havoc for all packages which depend on draw2d. We could use another package name or use a versioning system.
See also: http://golang.org/doc/faq#get_version

    Packages intended for public use should try to maintain backwards compatibility 
    as they evolve. The Go 1 compatibility guidelines are a good reference here: don't 
    remove exported names, encourage tagged composite literals, and so on. If 
    different functionality is required, add a new name instead of changing an old 
    one. If a complete break is required, create a new package with a new import path.

@stephenwithav 
Yes and no. The most suitable library for svgo is https://github.com/ajstarks/svgo. Unfortunately this uses integers instead of float coordinates. I've been working on a converter program `gofloat` which can rewrite svgo to float coordinates by manipulating the abstract syntax tree. This will be used by the author of svgo for the official float64 version of svgo:
https://github.com/ajstarks/svgo/issues/18

I hope to finish this in september. By writing the pdf backend, it seemed that draw2d needs some refactoring to truely support vectorial backends (e.g. for fonts, images, path construction, pushing/restoring contexts, ...). What I want to work on with @llgcode is a very low level common api, on top of which more high-level api(s) can be developed.

**Comment by llgcode** [comment]
-- Laurent.


On 17 August 2015 at 16:22, Stani <notifications@github.com> wrote:

> @llgcode <https://github.com/llgcode>
> Are we not breaking backwards compatibility now? I agree with the merged
> changes but
> ​​
> I am afraid this will cause havoc for all packages which depend on draw2d.
> ​​
> We could use another package name or use a versioning system.
> See also: http://golang.org/doc/faq#get_version
>
> Packages intended for public use should try to maintain backwards compatibility
> as they evolve. The Go 1 compatibility guidelines are a good reference here: don't
> remove exported names, encourage tagged composite literals, and so on. If
> different functionality is required, add a new name instead of changing an old
> one. If a complete break is required, create a new package with a new import path.
>
> ​Yes, I've move​

​image gc into draw2dimg ​package. I don't know actually how to manage
release. I agree
​
I am afraid
​ too, I was a bit fast when merging into master. ​I can write a migration
note/page that describes how to solve compilation errors.
What do you mean when you write "
​
We could use another package name
​"​(other than draw2d)?
I agree with a simple versioning system.

>  @stephenwithav <https://github.com/stephenwithav>
> Yes and no. The most suitable library for svgo is
> https://github.com/ajstarks/svgo. Unfortunately this uses integers
> instead of float coordinates. I've been working on a converter program
> gofloat which can rewrite svgo to float coordinates by manipulating the
> abstract syntax tree. This will be used by the author of svgo for the
> official float64 version of svgo:
> ajstarks/svgo#18 <https://github.com/ajstarks/svgo/issues/18>
>
​
​I'm not sure we need to use svgo, generating svg is trivial even if svgo
is a good package.
​

**Comment by stanim** [comment]
@llgcode 
With different package name, I mean something else as "draw2d". I am also not familiar with go versioning, you might find some inspiration here: https://github.com/golang/go/wiki/PackageManagementTools. I would be not happy if a package breaks unnoticed compatibility. I think it is better to revert the changes and first choose the right strategy as there will be much more changes coming. Also the old api should stay available somehow. Maybe you could create a v1 folder with the old code and a v2 folder with the new code. Than people have only to change the import path, but still can use the old api. That is a poor man's approach to versioning, probably there are better solutions.

For me it is totally fine if @stephenwithav implements a gc backend without svgo. Still it is probably better to wait until the new api of draw2d has stabilized. I'll probably still implement an svgo backend later, as svgo provides some advanced functionality with which i need to prepare the svg document and which draw2d does not support yet (e.g. different modes for color blending).

**Comment by llgcode** [comment]
Some packages have already made the change gonum/plot (
https://github.com/gonum/plot/pull/215) (
https://github.com/gonum/plot/issues/214)! I will pull request if necessary
into packages that uses draw2d if necessary.

-- Laurent.

**Comment by llgcode** [comment]
see the thread gonum/plot#214 .  If author wanted to vendor, they may do it with [GO15VENDOREXPERIMENT](https://github.com/golang/go/commit/183cc0cd41f06f83cb7a2490a499e3f9101befff). I think we just need to tag/release so that program/package author just need to vendor draw2d at a specified branch/commit/tag

**Comment by stanim** [comment]
You will need to document "`vendor draw2d at a specified branch/commit/tag`" in the readme. Maybe a more elegant solution is to automate this for the end user is: http://labix.org/gopkg.in

People can than just use:

    import  "gopkg.in/draw2d/v1"

This is linked to a specified branch/commit/tag and works out of the box with all the go tools. It was specifically designed for the problem we have now. The current unstable api can be made available as `gopkg.in/draw2d/v2`. Vendoring is still experimental and not everybody will be happy to be forced to do that.

**Comment by stephenwithav** [comment]
I agree with @stanim abut gopkg.in.

Tag commit `ce9c7f76f7d2ccc3600a29a4f0c9e2627fbf0ecb` as `v1` and you can use:

```go
import "gopkg.in/llgcode/draw2d.v1"
```

Example: http://gopkg.in/stephenwithav/draw2d.v1

**Pull request merged**
