### PR TITLE
GitHub imports

### PR DESCRIPTION
**Pull request by sbinet**
- migrate all imports to `github.com/llgcode/draw2d/...`
- apply `gofmt` and `goimports`

### CODE REVIEW

**Comment by llgcode** [comment]
Thanks for this great works!! I can't test now. does the tests works ? Can I close my eyes and merge the pull request? How can easily test your work without meging the pull request?

**Comment by sbinet** [comment]
according to https://help.github.com/articles/checking-out-pull-requests-locally
```sh
$ git fetch origin pull/34/head:toto
$ git checkout toto
```

as for the tests... there's no `make` target :) so I did this before submitting this PR:

```sh
$ go test ./draw2d/curve ./draw2d/raster 
ok  	github.com/llgcode/draw2d/draw2d/curve	0.491s
ok  	github.com/llgcode/draw2d/draw2d/raster	0.067s
```

**Comment by llgcode** [comment]
ok thanks for help. no make target for test ! :-)
Ok
I think i put my tests in cmd folder.
When I understanded how to checkout and test your work i will merge your
pull request

-- Laurent.

**Comment by sbinet** [comment]
I can add a `test` target to the `Makefile` :)

**Comment by llgcode** [comment]
lol. if you want

-- Laurent.

**Comment by sbinet** [comment]
done

I commented the draw2dgl (but this will be enabled back in the PR fixing `draw2dgl`) and x11 tests.
x11 tries to import the old `exp/x11` package...

**Comment by llgcode** [comment]
Thanks sebastien, this pull request has been merged.

**Pull request merged**
