### PR TITLE
doc: markdown-ify

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
needs #37

**Comment by llgcode** [comment]
Great Job. I think, I merge together with other pull request.

**Comment by sbinet** [comment]
which other PR? #37 or #38 ?
as I said on #38, I would need to rebase it when #36 is accepted (otherwise, it would lead to messy, bubbly and tangled history...)

**Comment by llgcode** [comment]
Ok then I accept now #36

**Comment by sbinet** [comment]
great. I just rebased #38

**Comment by llgcode** [comment]
Please can you tell me quickly how do you rebase your branch and why you to
do so. Seems that I just commit push things with git ! ;-)

-- Laurent.

**Comment by sbinet** [comment]
```sh
$ git checkout -b simpler-import-path sbinet/simpler-import-path
$ git fetch origin
$ git rebase origin/master
$ git push -f sbinet simpler-import-path
```

otherwise, you'd get these little annoying "cross-path" history lines:

```
* dba783c call reshape at start up to initiliaze opengl context
*   0abcba8 Merge branch 'sbinet-draw2dgl-with-go-gl'
|\  
| *   b1b8ea1 merge sbinet change
| |\  
|/ /  
| * 0eeb628 make: enable draw2dgl build+test
| * ef603db draw2dgl: remove unneeded GLVertex
| * c1b7f44 draw2dgl: de-stutter types
| * a8154b1 draw2dgl: use github.com/go-gl/{gl,glfw}
* | 6857de8 move postscript code to separate repository llgcode/ps
|/  
*   3d2a09c Merge branch 'sbinet-github-imports'
```
here, you merged my PR before I had time to rebase on top of your latest changes (6857de8)

it's no big deal, but, at scale, when branches diverge much more than that and/or when one tries to do code archeology (or assess code provenance) it can be a real headache (been there, done that).
headache which can be prevented by doing "branch trimming".

here is some additional doc, if you have a few cycles to burn :)
http://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by llgcode** [comment]
thanks seems to be clear :-)

-- Laurent.

**Pull request merged**
