### PR TITLE
Use github version of freetype library

### PR DESCRIPTION
**Pull request by Wayt**
Will fix error on `go get`
```
imports code.google.com/p/freetype-go/freetype/truetype: unable to detect version control system for code.google.com/ path
```

### CODE REVIEW

**Comment by llgcode** [comment]
Thanks.
I can't merge this patch with these imports github.com/wayt/draw2d, can you fix this using the command below so you can maintain your fork without changing imports.
```
 git remote add fork https://github.com/wayt/draw2d.git
```
reference:
http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html

**Comment by Wayt** [comment]
Sorry I didn't meant to include the 2nd commit, I've removed it.
When I tried a `go test` I had some errors because of the new version of the freetype library and I don't really known how to fix these.
```
Kenny:draw2d maxwayt (master) $ go test
# github.com/wayt/draw2d/draw2dimg
draw2dimg/ftgc.go:131: undefined: truetype.NoHinting
draw2dimg/ftgc.go:131: cannot use int32(gc.StackGraphicContext.Current.Scale) (type int32) as type fixed.Int26_6 in argument to gc.glyphBuf.Load
draw2dimg/ftgc.go:159: font.Kerning undefined (type *truetype.Font has no field or method Kerning)
draw2dimg/ftgc.go:166: cannot use int32(gc.StackGraphicContext.Current.Scale) (type int32) as type fixed.Int26_6 in argument to font.HMetric
draw2dimg/ftgc.go:166: cannot use font.HMetric(int32(gc.StackGraphicContext.Current.Scale), index).AdvanceWidth (type fixed.Int26_6) as type int32 in argument to fUnitsToFloat64
draw2dimg/ftgc.go:189: font.Kerning undefined (type *truetype.Font has no field or method Kerning)
draw2dimg/ftgc.go:191: undefined: truetype.NoHinting
draw2dimg/ftgc.go:191: cannot use int32(gc.StackGraphicContext.Current.Scale) (type int32) as type fixed.Int26_6 in argument to gc.glyphBuf.Load
draw2dimg/ftgc.go:206: cannot use int32(gc.StackGraphicContext.Current.Scale) (type int32) as type fixed.Int26_6 in argument to font.HMetric
draw2dimg/ftgc.go:206: cannot use font.HMetric(int32(gc.StackGraphicContext.Current.Scale), index).AdvanceWidth (type fixed.Int26_6) as type int32 in argument to fUnitsToFloat64
draw2dimg/ftgc.go:206: too many errors
```

**Comment by stanim** [comment]
This comment of Nigel Tao might be worth reading:

    Don't switch over to the github version just yet. I intend to make breaking API changes 
    over the next week or three.

https://github.com/google/gxui/issues/150

**Comment by llgcode** [comment]
ok thanks @stanim. 
Thanks @Wayt we will wait API stability of go freetype.

**Comment by Wayt** [comment]
Oh I missed this comment, thank you @stanim 
Meanwhile I'm using an old fork of your lib.

**Comment by nigeltao** [comment]
Sorry, the freetype-go redirection happened because it had to happen eventually, and code.google.com went read-only on August 24 (http://google-opensource.blogspot.com.au/2015/03/farewell-to-google-code.html) so I couldn't wait any longer.

I didn't announce it yet on the mailing lists because I still have other API changes to make, but I guess I should, if people are having "go get" problems.

To fix your build errors:

import two new packages:
"golang.org/x/exp/shiny/font"
"golang.org/x/image/math/fixed"

truetype.NoHinting becomes font.HintingNone
some values (like a font scale and an advance width) have changed from int32 to fixed.Int26_6
font.Kerning becomes font.Kern

**Comment by nigeltao** [comment]
golang-nuts post about the move to github.com/golang/freetype:
https://groups.google.com/d/topic/golang-nuts/tr-MftD7kbo/discussion

**Comment by llgcode** [comment]
Thanks @nigeltao . Our API is not stable now too. We use a tag v1 to help users know that we broke API. So in our V1 we continue to use code.google. Thanks for comment.

**Comment by jonseymour** [comment]
G'day,

I have created a fork of draw2d, ps and freetype which allows the fork to compile from master without any additional fiddling. I have no intention of maintaining this fork longer term, but it might be useful for people who need to fix a broken build because of the current issues with draw2d and freetype.

To make use of the fork, update your code to refer to ninjasphere/draw2d, ninjasphere/ps and ninjasphere/freetype where appropriate.

See https://github.com/ninjasphere/draw2d for the draw2d fork and use go get -d ./... to resolve the dependencies.

(Clean builds of the v1 tag don't work because the dependencies on code.google.com can't be resolved. It works if you have the code cloned already, but not otherwise).

**Comment by rbberry** [comment]
@jonseymour - You're my hero. Thanks!

**Comment by llgcode** [comment]
Thanks @jonseymour <https://github.com/jonseymour>


-- Laurent.

**Comment by llgcode** [comment]
Thanks @Wayt. we now have integrated freetype

**Pull request closed without merging**
