### PR TITLE
Fix Getting Started example in README.md.

### PR DESCRIPTION
**Pull request by stephenwithav**
SaveToPngFile is now in draw2dimg.

### CODE REVIEW

**Comment by llgcode** [comment]
I think I really like github. thx Stephen

**Comment by stephenwithav** [comment]
yw llgcode.

I need to send one more--as I forgot to change `.NewGraphicContext` to `draw2dimg`.

**Comment by stephenwithav** [comment]
Can you revert the change and reaccept this pull request?

**Comment by llgcode** [comment]
ok no problem

-- Laurent.

**Pull request merged**
